version: '3.8'
services:
  php-apache:
    container_name: php-apache
    build:
      context: ./.docker/php-apache
      dockerfile: Dockerfile
    volumes:
      - ./app/backend:/var/www/html/:rw
    ports:
      - 80:80
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    build:
      context: ./.docker/mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./.tmp/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MY_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: ./.docker/phpmyadmin
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
  mailhog:
    container_name: mailhog
    build:
      context: ./.docker/mailhog
      dockerfile: Dockerfile
    volumes:
      - ./.tmp/mailhog:/maildir:rw
    logging:
      driver: 'none'
    ports:
      - '1025:1025'
      - '8025:8025'
  redis:
    container_name: redis
    build:
      context: ./.docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./.tmp/redis:/data:rw
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./.docker/rabbitmq
      dockerfile: Dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./.tmp/rabbitmq:/var/lib/rabbitmq:rw
  elastic:
    container_name: elastic
    build:
      context: ./.docker/elastic
      dockerfile: Dockerfile
    ports:
      - '5601:5601'
      - '9200:9200'
      - '5044:5044'